### ISSUE TITLE
attach ACLs to topics?

### ISSUE THREAD

**Issue by ctramnitz** [Kappaware/jdctopic#1]
Can `jdctopic` also be used to attach ACLs to topics?

Great tool by the way, I'm going to create the yaml file using chef for full automation.
Topics and their settings will be maintained in attributes of a wrapper cookbook.

**Comment by SergeAlexandre** [comment]
Sorry, but currently jdctopic does not support ACL. No plan to do so in a near future. But contribution welcome :).

**Comment by ctramnitz** [comment]
Ok, thanks for the quick response.
However, I guess I have to get used to this before contributing, see my next issue
